function C = load_campagnola_matrices()
%LOAD_CAMPAGNOLA_MATRICES  Cell-type parameter matrices from Campagnola et al. 2022.
%
%   C = LOAD_CAMPAGNOLA_MATRICES() returns a struct of mouse cortical connectivity
%   and synapse parameters for 4 subclasses (Pyr, Pvalb, Sst, Vip), pooled across
%   layers, extracted from the Allen synaptic-physiology 'small' database.
%
%   Every matrix is 4x4 with rows = PREsynaptic type and cols = POSTsynaptic type,
%   ordered C.types = {'pyr','pvalb','sst','vip'}. Elements with fewer than 2
%   sampled pairs are NaN. Each per-connection metric has a matching sample-count
%   field <name>_n.
%
%   Fields (4x4 unless noted):
%     Connectivity : conn_prob, conn_prob_adj (distance-adjusted), n_probed, n_connected
%     Strength     : psp_amplitude (V), pulse_amp_90pct
%     STP          : stp_induction_50hz (>0 facilitating, <0 depressing),
%                    stp_recovery_250ms, variability_resting
%     Release model: ml_facilitation_amount, ml_facilitation_tau,
%                    ml_depression_amount, ml_depression_tau, ml_release_prob,
%                    ml_n_release_sites, ml_mini_amplitude
%     Kinetics     : latency, psc_rise_time, psc_decay_tau
%     SFA (4x1)    : sfa_adaptation_index, sfa_adaptation_index_n  (by postsynaptic type)
%     types        : {'pyr','pvalb','sst','vip'}  (row/col order)
%
%   Reads the committed CSVs under src/connectivity/campagnola/ (the version-
%   controlled source of truth), generated by
%   scripts/aisynphys/extract_campagnola_matrices.py. See campagnola/PROVENANCE.md
%   for the DB version and query details. (A campagnola_matrices.mat is also written
%   by the extractor as a convenience but is gitignored and not required here.)
%
%   Example:
%     C = load_campagnola_matrices();
%     i = @(t) find(strcmp(C.types, t));
%     C.conn_prob_adj(i('pyr'), i('pvalb'))   % Pyr -> Pvalb adjusted connection prob

    this_dir = fileparts(mfilename('fullpath'));
    csv_dir  = fullfile(this_dir, 'campagnola', 'csv');
    if ~isfolder(csv_dir)
        error('load_campagnola_matrices:missing', ...
            ['Campagnola CSVs not found at:\n  %s\n' ...
             'Regenerate with: scripts/aisynphys/run_extract.sh'], csv_dir);
    end

    C = struct();
    C.types = {'pyr', 'pvalb', 'sst', 'vip'};

    % Numeric 4x4 block of a labeled CSV (row 1 = header, col A = pre-type label).
    read4 = @(name) readmatrix(fullfile(csv_dir, [name '.csv']), 'Range', 'B2:E5');

    % Connectivity (no separate _n; n_probed / n_connected ARE the counts).
    for f = {'conn_prob', 'conn_prob_adj', 'n_probed', 'n_connected'}
        C.(f{1}) = read4(f{1});
    end

    % Per-connection metrics, each with a matching __n sample-count matrix.
    metrics = {'psp_amplitude', 'pulse_amp_90pct', ...
               'stp_induction_50hz', 'stp_recovery_250ms', 'variability_resting', ...
               'ml_facilitation_amount', 'ml_facilitation_tau', ...
               'ml_depression_amount', 'ml_depression_tau', 'ml_release_prob', ...
               'ml_n_release_sites', 'ml_mini_amplitude', ...
               'latency', 'psc_rise_time', 'psc_decay_tau'};
    for k = 1:numel(metrics)
        m = metrics{k};
        C.(m)          = read4(m);
        C.([m '_n'])   = read4([m '__n']);
    end

    % SFA: per-type adaptation_index (columns: type, adaptation_index, n).
    sfa_file = fullfile(this_dir, 'campagnola', 'sfa_adaptation_index.csv');
    C.sfa_adaptation_index   = readmatrix(sfa_file, 'Range', 'B2:B5');   % 4x1
    C.sfa_adaptation_index_n = readmatrix(sfa_file, 'Range', 'C2:C5');   % 4x1
end
