% example_SRNNCellTypePairs.m
%
% Three cell types with STD only, STF only, both mechanisms, and neither
% mechanism assigned to different presynaptic-to-postsynaptic routes.

close all; clear; clc;

n = 300;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Configure named routes: presynaptic type first, postsynaptic type second
synapse_config = struct();

% E -> E: STD only, with two timescales.
synapse_config.E.E.std = struct( ...
    'tau_rec', [0.25 1.5], ...
    'tau_rel', 0.25);

% E -> PV: omitted, so it has neither STD nor STF.

% E -> SST: STF only.
synapse_config.E.SST.stf = struct( ...
    'tau_dec', 1, ...
    'tau_fac', 0.25, ...
    'G', 2);

% PV -> E: both STD and STF.
synapse_config.PV.E.std = struct( ...
    'tau_rec', 0.6, ...
    'tau_rel', 0.3);
synapse_config.PV.E.stf = struct( ...
    'tau_dec', [0.4 1.5], ...
    'tau_fac', [0.2 0.4], ...
    'G', [1.5 2]);

model = SRNNCellTypePairs( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 3, ...
    'cell_type_names', {'E', 'PV', 'SST'}, ...
    'f', [1/3 1/3 1/3], ...
    'mu_tilde', F .* [3 -4 -4], ...
    'sigma_tilde', F .* [1 1 1], ...
    'n_a', [2 0 1], ...
    'tau_a', {[0.25 2], [], 1}, ...
    'c', [0.075 0 0.15], ...
    'synapse_config', synapse_config, ...
    'T_range', [0 20], ...
    'lya_method', 'benettin');

model.input_config.step_density = struct('E', 0.15, 'PV', 0, 'SST', 0);
model.build();
model.run();
model.plot();
model.plot_celltypes();
