% example_SRNNCellTypePairs_Pyr_SST.m
%
% Matched two-population reduction of example_SRNNCellTypePairs_canonical_cortical.
% Pyr and SST each occupy 50% of the network. Pyr->Pyr synapses are
% depressing, Pyr->SST synapses are strongly facilitating, SST->SST
% synapses are weakly depressing, and both cell types have SFA.

close all; clear; clc;

%% Matched network scale and baseline E/I weights
n = 400;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Pair-specific short-term plasticity
synapse_config = struct();
synapse_config.Pyr.Pyr.std = struct( ...
    'tau_rec', 1.0, ...
    'tau_rel', 0.25);
synapse_config.Pyr.SST.stf = struct( ...
    'tau_dec', 1.0, ...
    'tau_fac', 0.2, ...
    'G', 3.0);
synapse_config.SST.SST.std = struct( ...
    'tau_rec', 0.5, ...
    'tau_rel', 0.5);

model = SRNNCellTypePairs( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 2, ...
    'cell_type_names', {'Pyr', 'SST'}, ...
    'f', [0.5 0.5], ...
    'mu_tilde_relative', [3 -3], ...
    'sigma_tilde_relative', [1 1], ...
    'level_of_chaos', 0.3, ...
    'tau_a', {srnn_sfa_timescales(3), srnn_sfa_timescales(1)}, ...
    'tau_a', {logspace(log10(0.25), log10(10), 3), 2}, ...
    'c', [0.15/3 0.15], ...
    'synapse_config', synapse_config, ...
    'T_range', [0 20], ...
    'lya_method', 'benettin');

model.input_config.step_density = struct('Pyr', 0.15, 'SST', 0);

model.build();
model.run();
model.plot();
model.plot_celltypes();
