% example_SRNNCellTypes_additional_inhibitory.m
%
% Three-cell-type variant of test_SRNNCellTypes_defaults. The original 50%%
% inhibitory population is split evenly between an unadapted I population
% and I_adapt, which has one SFA timescale and one STD timescale.

close all; clear; clc;

%% Match the default network scale
n = 400;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Use the rounded piecewise sigmoid
S_a = 0.9;
S_c = 0.35;
phi = @(x) SRNNCellTypes.piecewiseSigmoid(x, S_a, S_c);
phi_derivative = @(x) SRNNCellTypes.piecewiseSigmoidDerivative(x, S_a, S_c);

%% Create E, unadapted I, and adapted I populations
model = SRNNCellTypes( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 3, ...
    'cell_type_names', {'E', 'I', 'I_adapt'}, ...
    'f', [0.5 0.25 0.25], ...
    'mu_tilde', F .* [3 -4 -4], ...
    'sigma_tilde', F .* [1 1 1], ...
    'n_a', [3 0 1], ...
    'tau_a', {logspace(log10(0.25), log10(10), 3), [], 1}, ...
    'c', [0.15/3, 0, 0.15], ...
    'n_b', [1 0 1], ...
    'tau_b_rec', {1, [], 1}, ...
    'tau_b_rel', [0.25 0.25 0.25], ...
    'S_a', S_a, ...
    'S_c', S_c, ...
    'activation_function', phi, ...
    'activation_function_derivative', phi_derivative);

% Keep external stimulation restricted to excitatory neurons.
model.input_config.step_density = struct('E', 0.15, 'I', 0, 'I_adapt', 0);

%% Build, run, and plot
model.build();
model.run();
model.plot();
model.plot_celltypes();