% example_SRNNCellTypes.m - Three-cell-type SRNN example.

close all; clear; clc;

n = 60;
indegree = 20;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

model = SRNNCellTypes( ...
    'n', n, 'indegree', indegree, ...
    'n_cellTypes', 3, ...
    'cell_type_names', {'E', 'PV', 'SST'}, ...
    'f', [0.8 0.1 0.1], ...
    'mu_tilde', F .* [3 -4 -3], ...
    'sigma_tilde', F .* [1 1 1], ...
    'n_a', [3 0 1], ...
    'tau_a', {[0.25 1 10], [], 2}, ...
    'c', [0.05 0 0.03], ...
    'n_b', [1 0 2], ...
    'tau_b_rec', {1, [], [0.5 2]}, ...
    'tau_b_rel', [0.25 0.25 0.4], ...
    'T_range', [-2 5], ...
    'lya_method', 'none');

model.input_config.step_density = struct('E', 0.15, 'PV', 0, 'SST', 0.05);
model.build();
model.run();
model.plot();
