% example_SRNNCellTypePairs_Pyr_VIP.m
%
% Matched two-population reduction of example_SRNNCellTypePairs_canonical_cortical.
% Pyr and VIP each occupy 50% of the network. Pyr->Pyr synapses are
% depressing, Pyr->VIP and VIP->VIP synapses are weakly facilitating, and
% both cell types have SFA.

close all; clear; clc;
addpath(fileparts(fileparts(mfilename('fullpath'))));
setup_paths();

%% Matched network scale and baseline E/I weights
n = 400;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Pair-specific short-term plasticity
synapse_config = struct();
synapse_config.Pyr.Pyr.std = struct( ...
    'tau_rec', 1.0, ...
    'tau_rel', 0.25);
synapse_config.Pyr.VIP.stf = struct( ...
    'tau_dec', 0.5, ...
    'tau_fac', 0.5, ...
    'G', 1.5);
synapse_config.VIP.VIP.stf = struct( ...
    'tau_dec', 0.5, ...
    'tau_fac', 0.5, ...
    'G', 1.5);

model = SRNNCellTypePairs( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 2, ...
    'cell_type_names', {'Pyr', 'VIP'}, ...
    'f', [0.5 0.5], ...
    'mu_tilde', F .* [3 -3], ...
    'sigma_tilde', F .* [1 1], ...
    'level_of_chaos', 0.3, ...
    'n_a', [3 1], ...
    'tau_a', {logspace(log10(0.25), log10(10), 3), 1}, ...
    'c', [0.15/3 0.15], ...
    'synapse_config', synapse_config, ...
    'T_range', [0 20], ...
    'lya_method', 'benettin');

model.input_config.step_density = struct('Pyr', 0.15, 'VIP', 0);

model.build();
model.run();
model.plot();
model.plot_celltypes();
