% test_SRNNCellTypes_parity_lyapunov.m - E/I parity and Lyapunov smoke test.

clear; clc;

%% Two-type dynamics match SRNNModel2 for deterministic full connectivity
% SRNNModel2 takes the RMT means in multiples of F = 1/sqrt(n*alpha*(2-alpha));
% with n = indegree = 6 (fully connected, alpha = 1) F = 1/sqrt(6), so the
% absolute 0.05 / -0.07 that SRNNCellTypes takes directly become 0.05*sqrt(6)
% and -0.07*sqrt(6) here.
F_parity = 1 / sqrt(6);
shared = {'n', 6, 'indegree', 6, 'f', 0.5, ...
    'n_a_E', 1, 'n_a_I', 0, 'tau_a_E', 0.5, 'c_E', 0.05, ...
    'n_b_E', 0, 'n_b_I', 1, 'tau_b_I_rec', 0.8, ...
    'tau_b_I_rel', 0.25, ...
    'mu_E_tilde_relative', 0.05/F_parity, 'mu_I_tilde_relative', -0.07/F_parity, ...
    'sigma_E_tilde_relative', 0, 'sigma_I_tilde_relative', 0, ...
    'S_a', 0.9, 'S_c', 0.40, ...
    'T_range', [0 0.1], 'lya_method', 'none', 'x0_std', 0};
old_model = SRNN2TestAccess(shared{:});
old_model.build();

% S_a / S_c are pinned on BOTH models rather than left to class defaults: this
% comparison is only meaningful if the nonlinearity is identical, and a divergent
% default is exactly what used to make the RHS assertion below fail.
new_model = SRNNCellTypes( ...
    'n', 6, 'indegree', 6, ...
    'n_cellTypes', 2, 'cell_type_names', {'E', 'I'}, ...
    'f', [0.5 0.5], 'mu_tilde', [0.05 -0.07], ...
    'sigma_tilde', [0 0], ...
    'n_a', [1 0], 'tau_a', {0.5, []}, 'c', [0.05 0.05], ...
    'n_b', [0 1], 'tau_b_rec', {[], 0.8}, ...
    'tau_b_rel', [0.25 0.25], ...
    'S_a', 0.9, 'S_c', 0.40, ...
    'T_range', [0 0.1], 'lya_method', 'none', 'x0_std', 0);
new_model.build();

assert(max(abs(full(old_model.W) - full(new_model.W)), [], 'all') < 1e-14);
old_params = old_model.get_params();
new_params = new_model.get_params();
zero_input = griddedInterpolant([0; 1], zeros(2, 6), 'linear', 'none');
old_params.u_interpolant = zero_input;
new_params.u_interpolant = zero_input;
state = [0.2; 0.1; 0.3; 0.8; 0.7; 0.9; linspace(-0.2, 0.3, 6)'];
old_rhs = SRNN2TestAccess.rhs(0, state, old_params);
new_rhs = SRNNCellTypes.dynamics_fast(0, state, new_params);
assert(max(abs(old_rhs - new_rhs)) < 1e-12);

%% Benettin and QR paths produce consistent largest exponents
% T_range must be long enough for the two estimators to CONVERGE, or this
% assertion measures transient disagreement rather than agreement. On this tiny
% 6-neuron network the gap falls 0.14 -> 0.12 -> 0.012 as T goes 3 -> 10 -> 30,
% so [-1 30] leaves ~6x margin on the 0.08 tolerance. (At the previous [-1 3]
% the test passed only by luck, and a small change in the nonlinearity centre
% was enough to push it over.)
base = {'n', 6, 'indegree', 2, ...
    'n_cellTypes', 2, 'cell_type_names', {'A', 'B'}, ...
    'f', [0.5 0.5], 'mu_tilde', [0.05 -0.07], ...
    'sigma_tilde', [0.01 0.01], ...
    'n_a', [1 0], 'tau_a', {0.5, []}, ...
    'n_b', [0 1], 'tau_b_rec', {[], 0.8}, ...
    'S_a', 0.9, 'S_c', 0.40, ...
    'T_range', [-1 30], 'fs', 200, 'store_full_state', true, ...
    'x0_std', 0.01};

benettin = SRNNCellTypes(base{:}, 'lya_method', 'benettin');
benettin.build(); benettin.run();
qr_model = SRNNCellTypes(base{:}, 'lya_method', 'qr');
qr_model.build(); qr_model.run();

largest_benettin = benettin.lya_results.LLE;
largest_qr = qr_model.lya_results.LE_spectrum(1);
fprintf('Benettin=%+.4f, QR=%+.4f, difference=%.4f\n', ...
    largest_benettin, largest_qr, abs(largest_benettin - largest_qr));
assert(isfinite(largest_benettin) && isfinite(largest_qr));
assert(abs(largest_benettin - largest_qr) < 0.08);

fprintf('test_SRNNCellTypes_parity_lyapunov: ALL TESTS PASSED\n');
