% example_SRNNCellTypePairs_Pyr_Pvalb.m
%
% Matched two-population reduction of example_SRNNCellTypePairs_canonical_cortical.
% Pyr and Pvalb each occupy 50% of the network. Pyr->Pyr and Pyr->Pvalb
% synapses are depressing; Pvalb outputs are strongly depressing. Pyr has
% SFA; fast-spiking Pvalb does not.

close all; clear; clc;

%% Matched network scale and baseline E/I weights
n = 400;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Pair-specific short-term depression
synapse_config = struct();
synapse_config.Pyr.Pyr.std = struct( ...
    'tau_rec', 1.0, ...
    'tau_rel', 0.25);
synapse_config.Pyr.Pvalb.std = struct( ...
    'tau_rec', 1.0, ...
    'tau_rel', 0.25);
synapse_config.Pvalb.Pyr.std = struct( ...
    'tau_rec', 1.5, ...
    'tau_rel', 0.20);
synapse_config.Pvalb.Pvalb.std = struct( ...
    'tau_rec', 1.5, ...
    'tau_rel', 0.20);

model = SRNNCellTypePairs( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 2, ...
    'cell_type_names', {'Pyr', 'Pvalb'}, ...
    'f', [0.5 0.5], ...
    'mu_tilde_relative', [3 -3], ...
    'sigma_tilde_relative', [1 1], ...
    'level_of_chaos', 0.3, ...
    'tau_a', {log_ladder(0.25, 10, 3), []}, ...
    'tau_a', {logspace(log10(0.25), log10(10), 3), []}, ...
    'c', [0.15/3 0], ...
    'synapse_config', synapse_config, ...
    'T_range', [0 20], ...
    'lya_method', 'benettin');

model.input_config.step_density = struct('Pyr', 0.15, 'Pvalb', 0);

model.build();
model.run();
model.plot();
model.plot_celltypes();
