% example_SRNNCellTypePairs_SRNNModel2_defaults_chaos2_with_SST.m
%
% SST extension of example_SRNNCellTypePairs_SRNNModel2_defaults_chaos2.
% The original inhibitory population is divided evenly between generic I
% and SST neurons, preserving the total 50/50 excitatory-inhibitory balance.
% E->SST synapses are strongly facilitating, and SST neurons do not have
% SFA. All other settings match the two-population baseline.

close all; clear; clc;

%% Match the baseline network scale
n = 300;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Use the rounded piecewise sigmoid
S_a = 0.9;
S_c = 0.4;
phi = @(x) SRNNCellTypePairs.piecewiseSigmoid(x, S_a, S_c);
phi_derivative = ...
    @(x) SRNNCellTypePairs.piecewiseSigmoidDerivative(x, S_a, S_c);

%% Pair-specific short-term plasticity
synapse_config = struct();

% Preserve the baseline one-timescale depression on E->E and E->I.
synapse_config.E.E.std = struct( ...
    'tau_rec', 2.0, ...
    'tau_rel', 0.5);
% synapse_config.E.I.std = struct( ...
%     'tau_rec', 2.0, ...
%     'tau_rel', 0.5);

% Strongly facilitating excitation of SST neurons.
synapse_config.E.SST.stf = struct( ...
    'tau_dec', 4.0, ...
    'tau_fac', 0.5, ...
    'G', 3.0);

model = SRNNCellTypePairs( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 3, ...
    'cell_type_names', {'E', 'I', 'SST'}, ...
    'f', [0.5 0.25 0.25], ...
    'mu_tilde_relative', [3 -4 -4], ...
    'sigma_tilde_relative', [1 1 1], ...
    'level_of_chaos', 2.0, ...
    'tau_a', {log_ladder(0.25, 10, 3), [], log_ladder(0.25, 10, 2)}, ...
    'tau_a', {logspace(log10(0.25), log10(10), 3), [], [1 5]}, ...
    'c', [0.5/3, 0.5/3, 0.5/2], ...
    'synapse_config', synapse_config, ...
    'tau_d', 0.1, ...
    'S_a', S_a, ...
    'S_c', S_c, ...
    'activation_function', phi, ...
    'activation_function_derivative', phi_derivative, ...
    'fs', 400, ...
    'T_range', [0 30], ...
    'x0_std', 0.1, ...
    'rng_seeds', [1 2]+3, ...
    'lya_method', 'benettin');

% Keep external stimulation restricted to excitatory neurons.
model.input_config.step_density = struct('E', 0.15, 'I', 0, 'SST', 0);

%% Build, simulate, and visualize
model.build();
model.run();
model.plot();
model.plot_celltypes();
