% example_SRNNCellTypePairs_SRNNModel2_defaults_chaos2.m
%
% SRNNCellTypePairs counterpart to SRNNModel2('level_of_chaos', 2.0,
% 'n_a_E', 3, 'n_b_E', 1).
% This is the two-population baseline for later tests of whether adding an
% SST population can stabilize a strongly coupled E/I reservoir.
%
% This version uses the rounded piecewise sigmoid instead of the default
% logistic activation.

close all; clear; clc;

%% Match the SRNNModel2 network defaults
n = 300;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Use the rounded piecewise sigmoid
S_a = 0.9;
S_c = 0.4;
phi = @(x) SRNNCellTypePairs.piecewiseSigmoid(x, S_a, S_c);
phi_derivative = ...
    @(x) SRNNCellTypePairs.piecewiseSigmoidDerivative(x, S_a, S_c);

%% Match three-timescale E-cell SFA and one-timescale E-cell STD
% SRNNModel2 uses one presynaptic E STD bank for all targets. The pair model
% represents that setting with identical E->E and E->I route parameters.
synapse_config = struct();
synapse_config.E.E.std = struct( ...
    'tau_rec', 2.0, ...
    'tau_rel', 0.15);
synapse_config.E.I.std = struct( ...
    'tau_rec', 2.0, ...
    'tau_rel', 0.15);

model = SRNNCellTypePairs( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 2, ...
    'cell_type_names', {'E', 'I'}, ...
    'f', [0.5 0.5], ...
    'mu_tilde_relative', [3 -4], ...
    'sigma_tilde_relative', [1 1], ...
    'level_of_chaos', 5.0, ...
    'tau_a', {log_ladder(0.25, 10, 3), []}, ...
    'tau_a', {logspace(log10(0.25), log10(10), 3), []}, ...
    'c', [0.5/3 0.5/3], ...
    'synapse_config', synapse_config, ...
    'tau_d', 0.1, ...
    'S_a', S_a, ...
    'S_c', S_c, ...
    'activation_function', phi, ...
    'activation_function_derivative', phi_derivative, ...
    'fs', 400, ...
    'T_range', [0 50], ...
    'x0_std', 0.1, ...
    'rng_seeds', [1 2]+3, ...
    'lya_method', 'benettin');

% Match SRNNModel2's default type-selective sparse stimulus.
model.input_config.step_density = struct('E', 0.15, 'I', 0);

%% Build, simulate, and visualize
model.build();
model.run();
model.plot();
model.plot_celltypes();
