% example_SRNNCellTypePairs_canonical_cortical.m
%
% Basic Pyr-Pvalb-SST-VIP circuit inspired by Campagnola et al. (2022),
% "Local connectivity and synaptic dynamics in mouse and human neocortex."
%
% Qualitative STP assignments from the paper:
%   Pyr   -> Pyr   : depressing
%   Pyr   -> Pvalb : depressing
%   Pvalb -> Pyr   : depressing
%   Pvalb -> Pvalb : strongly depressing
%   Pyr   -> VIP   : weakly facilitating
%   Pyr   -> SST   : strongly facilitating
%   SST   -> SST   : weakly depressing
%   SST   -> VIP   : strongly facilitating
%   VIP   -> SST   : weakly facilitating
%   VIP   -> VIP   : weakly facilitating
%
% Pyr, SST, and VIP have SFA in this example, whereas fast-spiking Pvalb
% does not. This SFA assignment is a modeling assumption rather than a
% parameterization fitted by Campagnola et al. The numerical STD/STF and
% SFA parameters below are illustrative qualitative strengths, not fitted
% values from the paper.
%
% SRNNCellTypePairs currently uses uniform connection probability and
% presynaptic-type-specific weight statistics. The example therefore models
% the canonical route-dependent synaptic dynamics, not the paper's complete
% pair-specific connection probabilities and strengths.

close all; clear; clc;

%% Network scale and presynaptic weight signs
n = 400;
indegree = 100;
alpha = indegree / n;
F = 1 / sqrt(n * alpha * (2 - alpha));

%% Pair-specific short-term plasticity
synapse_config = struct();

% Recurrent pyramidal excitation is depressing.
synapse_config.Pyr.Pyr.std = struct( ...
    'tau_rec', 1.0, ...
    'tau_rel', 0.25);

% Depressing interactions between pyramidal and Pvalb cells.
synapse_config.Pyr.Pvalb.std = struct( ...
    'tau_rec', 1.0, ...
    'tau_rel', 0.25);
synapse_config.Pvalb.Pyr.std = struct( ...
    'tau_rec', 1.5, ...
    'tau_rel', 0.20);

% Recurrent Pvalb inhibition is strongly depressing.
synapse_config.Pvalb.Pvalb.std = struct( ...
    'tau_rec', 1.5, ...
    'tau_rel', 0.20);

% Weak facilitating excitation of VIP cells.
synapse_config.Pyr.VIP.stf = struct( ...
    'tau_dec', 0.5, ...
    'tau_fac', 0.5, ...
    'G', 1.5);

% Strong facilitating excitation of SST cells.
synapse_config.Pyr.SST.stf = struct( ...
    'tau_dec', 1.0, ...
    'tau_fac', 0.2, ...
    'G', 3.0);

% Recurrent SST inhibition is weakly depressing.
synapse_config.SST.SST.std = struct( ...
    'tau_rec', 0.5, ...
    'tau_rel', 0.5);

% Reciprocal SST-VIP inhibition: strong SST->VIP and weak VIP->SST STF.
synapse_config.SST.VIP.stf = struct( ...
    'tau_dec', 1.0, ...
    'tau_fac', 0.2, ...
    'G', 3.0);
synapse_config.VIP.SST.stf = struct( ...
    'tau_dec', 0.5, ...
    'tau_fac', 0.5, ...
    'G', 1.5);

% Recurrent VIP inhibition is weakly facilitating.
synapse_config.VIP.VIP.stf = struct( ...
    'tau_dec', 0.5, ...
    'tau_fac', 0.5, ...
    'G', 1.5);

%% Construct the four-cell-type reservoir
% Fractions and weight means give an approximately balanced population-
% weighted recurrent mean while retaining strong Pvalb inhibition.
model = SRNNCellTypePairs( ...
    'n', n, ...
    'indegree', indegree, ...
    'n_cellTypes', 4, ...
    'cell_type_names', {'Pyr', 'Pvalb', 'SST', 'VIP'}, ...
    'f', [0.7 0.1 0.1 0.1], ...
    'mu_tilde_relative', [3 -9 -7 -5], ...
    'sigma_tilde_relative', [1 1 1 1], ...
    'level_of_chaos', 0.3, ...
    'tau_a', {log_ladder(0.25, 10, 3), [], log_ladder(0.25, 10, 1), log_ladder(0.25, 10, 1)}, ...
    'tau_a', {logspace(log10(0.25), log10(10), 3), [], 2, 1}, ...
    'c', [0.15/3 0 0.15 0.15], ...
    'synapse_config', synapse_config, ...
    'T_range', [0 20], ...
    'lya_method', 'benettin');

% Stimulate pyramidal neurons only.
model.input_config.step_density = struct( ...
    'Pyr', 0.15, ...
    'Pvalb', 0, ...
    'SST', 0, ...
    'VIP', 0);

%% Build, simulate, and visualize
model.build();
model.run();
model.plot();
model.plot_celltypes();
