% test_sensitivity_refactor.m
% Quick verification that the refactored sensitivity analysis works
% Uses 3 levels and 3 reps for fast execution

setup_paths();

%% Test 1: Scalar parameter sensitivity (level_of_chaos)
fprintf('\n=== Test 1: Scalar param (level_of_chaos) ===\n');
psa1 = ParamSpaceAnalysis2(...
    'n_levels', 3, ...
    'batch_size', 25, ...
    'note', 'test_scalar', ...
    'randomize_order', false, ...
    'use_parallel', true, ...
    'verbose', true ...
    );

psa1.add_grid_parameter('level_of_chaos', [0.5, 2.5]);
psa1.add_grid_parameter('reps', 1:3);

psa1.run();
fprintf('Test 1 PASSED: scalar sensitivity run completed\n');

% Test plotting
psa1.plot_sensitivity('metric', 'LLE');
fprintf('Test 1 plot PASSED\n');
close all;

%% Test 2: Vector parameter sensitivity (tau_a_E)
fprintf('\n=== Test 2: Vector param (tau_a_E) ===\n');
psa2 = ParamSpaceAnalysis2(...
    'n_levels', 3, ...
    'batch_size', 25, ...
    'note', 'test_vector', ...
    'randomize_order', false, ...
    'use_parallel', true, ...
    'verbose', true ...
    );

psa2.set_conditions({struct('name', 'sfa_and_std', 'n_a_E', 3, 'n_b_E', 1)});

psa2.add_vector_parameter('tau_a_E', ...
    'vary_element', 'last', ...
    'fixed_value', 0.25, ...
    'vary_range', [5, 60], ...
    'n_elements', 3, ...
    'spacing', 'log', ...
    'level_spacing', 'linear');

psa2.add_grid_parameter('reps', 1:3);

% Verify vectors were generated correctly
fprintf('Vector param lookup:\n');
for i = 1:3
    fprintf('  Level %d: tau_a_E = [%s]\n', i, ...
        num2str(psa2.vector_param_config.tau_a_E.vary_range));
end

psa2.run();
fprintf('Test 2 PASSED: vector sensitivity run completed\n');

psa2.plot_sensitivity('metric', 'LLE', 'hist_range', [-0.3, 0.1]);
fprintf('Test 2 plot PASSED\n');
close all;

fprintf('\n=== All tests PASSED ===\n');
