function out = fig_example_timeseries(cfg)
% FIG_EXAMPLE_TIMESERIES Example SRNN time series at the paper's operating point.
%
%   out = FIG_EXAMPLE_TIMESERIES()
%   out = FIG_EXAMPLE_TIMESERIES('preset_name', p, 'out_dir', d)
%
% One realization of the model the rest of the paper analyses: the stimulus, the
% dendritic state x, the firing rate r, the synaptic output, and the adaptation
% and depression variables, under SFA + STD.
%
% PORTED. This was SRNNModel2 at class defaults with the LOGISTIC nonlinearity,
% n = 300, level_of_chaos = 1 and no noise -- while every sweep figure in the
% paper is SRNNCellTypePairs, piecewise, n = 500, S_c = 0.2, sigma_u_noise =
% 0.025. It was the "here is what the model does" figure showing a different
% model from the one being characterised. It now takes the same preset as the
% sweeps, so the example and the statistics describe one network.
%
% See also: paper_config, srnn_param_preset, SRNNCellTypePairs

arguments
    cfg.preset_name (1,:) char    = 'celltype_pairs_Sc0p2_noise0p025_dualStd_4cond'
    cfg.out_dir     (1,:) char    = ''
    cfg.condition   (1,:) char    = 'sfa_and_std'
    cfg.rng_seeds   (1,2) double  = [1 2]
    cfg.T_range     (1,2) double  = [0 20]
    cfg.save        (1,1) logical = true
    cfg.visible     (1,1) logical = true
    cfg.run_dir     (1,:) char    = ''      % unused; accepted for a uniform call
end

setup_paths();
out_dir = default_out_dir(cfg.out_dir, mfilename('fullpath'));

%% Build the model from the preset, under one adaptation condition
% build_from_preset merges preset + condition, selects the integrator the
% preset's noise requires, and builds. See its header for the three traps it
% exists to close (integrator selection, flat argument expansion, and the fact
% that adaptation counts live in the CONDITION, never in a preset).
[model, info] = build_from_preset(cfg.preset_name, cfg.condition, ...
    'rng_seeds', cfg.rng_seeds, 'T_range', cfg.T_range, ...
    'fs', 400, 'lya_method', 'none');
model_class = info.model_class;
solver      = info.ode_solver;

model.run();

[fig_handle, ~] = model.plot();
if ~cfg.visible; set(fig_handle, 'Visible', 'off'); end

%% Save
out = struct('figs', fig_handle, 'files', {{}}, 'source', 'simulated inline');
if cfg.save
    save_figure_stable(out_dir, 'fig_example_timeseries', fig_handle);
    out.files = existing_outputs(out_dir, 'fig_example_timeseries');

    write_figure_readme(out_dir, struct( ...
        'tag',    'fig_example_timeseries', ...
        'title',  'Stability_Manuscript figure: example time series', ...
        'script', 'fig_example_timeseries.m', ...
        'what',   ['One realization of the network the rest of the paper ' ...
                   'analyses: stimulus, dendritic state x, firing rate r, ' ...
                   'synaptic output, and the adaptation/depression states, ' ...
                   'under the SFA + STD condition. Simulated inline -- there ' ...
                   'is no saved run behind it.'], ...
        'how',    ['Model built from the named preset under one adaptation ' ...
                   'condition, then model.plot(). The integrator is chosen ' ...
                   'from the preset: a preset carrying sigma_u_noise > 0 ' ...
                   'requires a stochastic scheme (sra1), because this figure ' ...
                   'does not go through analysis_run_config, which is what ' ...
                   'selects one for the sweeps.'], ...
        'source', struct('preset', cfg.preset_name, 'model_class', model_class, ...
                         'condition', cfg.condition, ...
                         'rng_seeds', cfg.rng_seeds, 'ode_solver', solver), ...
        'settings', figure_settings(model), ...
        'figures', {out.files}, ...
        'notes',  ['PORTED from SRNNModel2. This figure used to show a ' ...
                   'different model from every other figure in the paper -- ' ...
                   'logistic nonlinearity, n = 300, no noise -- while the ' ...
                   'sweeps were SRNNCellTypePairs, piecewise, n = 500, with ' ...
                   'noise. It now takes the same preset as the sweeps.']));
end
end
