classdef SRNNModelBase < handle
    % SRNNMODELBASE Abstract base for rate-network reservoir models.
    %
    % Holds the type-agnostic machinery shared by all SRNN model variants:
    % construction / name-value parsing, the build() template, ODE integration
    % (run), Lyapunov analysis (Benettin + QR), decimation, generic
    % eigenvalue/Lyapunov plotting, and the activation-function library.
    %
    % Model-specific behavior (connectivity, state packing, the RHS/Jacobian
    % numeric kernels, and E/I-vs-cell-type plotting) is supplied by concrete
    % subclasses through the abstract hooks declared below:
    %   build_network, build_stimulus, validate, get_params,
    %   decimate_and_unpack, eval_dynamics, eval_jacobian
    %
    % The eval_dynamics / eval_jacobian hooks are the numeric "seam": run() and
    % compute_lyapunov() dispatch the RHS and Jacobian through them (instead of
    % a hardcoded static kernel) so each subclass plugs in its own dynamics.
    %
    % Concrete subclass: SRNNModel2 (E/I).
    %
    % See also: SRNNModel2, SRNN_ESN_reservoir


    %% Network Architecture Properties
    properties
        n = 300                     % Total number of neurons
        indegree = 100              % Expected in-degree

        level_of_chaos = 1.0        % Scaling factor for W
        rescale_by_abscissa = false % Whether to apply 1/abscissa_0 scaling
    end

    %% Dynamics Properties
    properties
        tau_d = 0.1                 % Dendritic time constant (s)
        activation_function         % Activation function handle
        activation_function_derivative  % Derivative of activation function
        S_a = 0.9                   % Activation function parameter a
        S_c = 0.35                  % Activation function parameter c (center)
    end

    %% Simulation Settings Properties
    properties
        fs = 400                    % Sampling frequency (Hz)
        T_range = [0, 50]           % Simulation time interval [start, end]
        T_plot                      % Plotting time interval (defaults to T_range)
        ode_solver = @ode45         % ODE solver function handle
        ode_opts                    % ODE solver options struct
        x0_std = 0.1                % Std dev of the random initial dendritic state x0 (0 = deterministic x0=0)
    end

    %% Input Configuration Properties
    properties
        input_config                % Struct with stimulus parameters
        u_ex_scale = 1.0            % Scaling factor for external input
        rng_seeds = [1 2]           % RNG seeds [network, stimulus, etc]
        reps = 1                    % Repetition index (reserved for future use; typically unused)
    end

    %% Lyapunov Settings Properties
    properties
        lya_method = 'benettin'     % Lyapunov method: 'benettin', 'qr', or 'none'
        lya_T_interval              % Time interval for Lyapunov computation
        filter_local_lya = false    % Whether to filter local Lyapunov exponent
        lya_filter_order = 2        % Butterworth filter order
        lya_filter_cutoff = 0.25    % Normalized cutoff frequency (fraction of Nyquist)
    end

    %% Storage Options Properties
    properties
        store_full_state = false    % Whether to keep full S_out in memory
        store_decimated_state = true % Whether to keep decimated plot data
        plot_deci                   % Decimation factor for plotting (computed from fs/plot_freq if not set)
        plot_freq = 10              % Target plotting frequency (Hz)
    end

    %% RMT Dependent Properties (computed from tilde parameters)
    properties (Dependent)
        alpha               % Sparsity = indegree/n
    end

    %% Computed Properties (SetAccess = protected for subclass access)
    properties (SetAccess = protected)
        W                           % Connection matrix (n x n)
        is_built = false            % Flag indicating if network is initialized

        % External input (generated by build)
        t_ex                        % Time vector for external input
        u_ex                        % External input matrix (n x nt)
        u_interpolant               % griddedInterpolant for external input (avoids persistent vars)
        S0                          % Initial state vector
        cached_params               % Cached params struct (set by build)
    end

    %% Results Properties (conditionally stored)
    properties (SetAccess = protected)
        t_out                       % Time vector from ODE solver
        S_out                       % State trajectory (nt x N_sys_eqs)
        plot_data                   % Struct with decimated data for plotting
        lya_results                 % Lyapunov analysis results struct
        has_run = false             % Flag indicating if simulation has run
    end

    %% Constructor
    methods
        function obj = SRNNModelBase(varargin)
            % SRNNMODELBASE Constructor with name-value pairs (shared by all subclasses)
            %
            % Subclasses forward to this via obj@SRNNModelBase(varargin{:}). It
            % applies defaults (set_defaults, dispatched to the subclass override),
            % parses name-value pairs reflectively, and derives plot_deci.

            % Set default values (dispatches to the most-derived set_defaults)
            obj.set_defaults();

            % Parse name-value pairs
            for i = 1:2:length(varargin)
                if isprop(obj, varargin{i})
                    obj.(varargin{i}) = varargin{i+1};
                else
                    warning('SRNNModel:UnknownProperty', 'Unknown property: %s', varargin{i});
                end
            end

            % Compute plot_deci from fs and plot_freq if not explicitly set
            if isempty(obj.plot_deci)
                obj.plot_deci = round(obj.fs / obj.plot_freq);
            end
        end
    end

    %% Abstract hooks — implemented by concrete subclasses
    % The model-specific contract that the base machinery (build/run/lyapunov)
    % dispatches into. Declaring them here also roots their protected access in
    % the base, so base methods may legally invoke a subclass's protected
    % implementation (build_network, decimate_and_unpack, eval_*).
    methods (Abstract, Access = protected)
        build_network(obj)                       % construct connectivity matrix obj.W
        build_stimulus(obj)                      % generate stimulus, interpolant, and S0
        validate(obj)                            % check parameter consistency
        decimate_and_unpack(obj)                 % decimate S_out into obj.plot_data
        dS_dt = eval_dynamics(obj, t, S, params) % RHS seam  -> subclass numeric kernel
        J = eval_jacobian(obj, S, params)        % Jacobian seam -> subclass numeric kernel
    end

    methods (Abstract)
        params = get_params(obj)                 % pack the params struct (read by drivers)
    end

    %% Dependent Property Getters
    methods
        function val = get.alpha(obj)
            val = obj.indegree / obj.n;
        end

    end

    %% Public Methods
    methods
        function build(obj)
            % BUILD Initialize the network: create W, generate stimulus, cache params
            %
            % This method must be called before run(). It delegates to three
            % protected sub-methods that subclasses can override:
            %   1. build_network()   - Create W matrix
            %   2. build_stimulus()  - Generate external stimulus, interpolant, S0
            %   3. finalize_build()  - Validate and cache params

            obj.build_network();
            obj.build_stimulus();
            obj.finalize_build();
        end

        function run(obj)
            % RUN Execute the ODE simulation
            %
            % This method integrates the SRNN equations and optionally computes
            % Lyapunov exponents. Results are stored based on storage options.

            if ~obj.is_built
                error('SRNNModel:NotBuilt', 'Model must be built before running. Call build() first.');
            end

            % Use cached params struct
            params = obj.cached_params;

            % Set up ODE options
            dt = 1 / obj.fs;
            if isempty(obj.ode_opts)
                jac_wrapper = @(t, S) obj.eval_jacobian(S, params);
                obj.ode_opts = odeset('RelTol', 1e-9, 'AbsTol', 1e-9, 'MaxStep', dt, 'Jacobian', jac_wrapper);
            end

            % Define RHS function using closure (avoids OOP overhead)
            % Cache interpolant and params to avoid property access on every call
            u_interp = obj.u_interpolant;
            params.u_interpolant = u_interp;  % Add to params for dynamics_fast
            rhs = @(t, S) obj.eval_dynamics(t, S, params);

            % Integrate
            fprintf('Integrating equations\n');
            tic
            [t_raw, S_raw] = obj.ode_solver(rhs, obj.t_ex, obj.S0, obj.ode_opts);
            integration_time = toc;
            fprintf('Integration complete in %.2f seconds.\n', integration_time);

            % Verify output times match input times
            if length(t_raw) ~= length(obj.t_ex) || max(abs(t_raw - obj.t_ex)) > 1e-9
                error('SRNNModel:TimeMismatch', 'ODE solver output times do not match input times. Max diff: %.2e', max(abs(t_raw(:) - obj.t_ex(:))));
            end

            % Store temporarily for Lyapunov and decimation
            obj.t_out = t_raw;
            obj.S_out = S_raw;

            % Compute Lyapunov exponents
            if ~strcmpi(obj.lya_method, 'none')
                obj.compute_lyapunov();
                % Filter local Lyapunov exponent (before decimation to avoid edge effects)
                if obj.filter_local_lya
                    obj.filter_lyapunov();
                end
            end

            % Decimate and unpack for plotting
            if obj.store_decimated_state
                obj.decimate_and_unpack();
            end

            % Clear full state if not storing (free memory)
            if ~obj.store_full_state
                obj.S_out = [];
            end

            obj.has_run = true;
            fprintf('Simulation complete.\n');
        end

        function compute_lyapunov(obj)
            % COMPUTE_LYAPUNOV Compute Lyapunov exponents based on lya_method

            if isempty(obj.S_out)
                error('SRNNModel:NoStateData', 'State data not available. Set store_full_state=true or call before clearing.');
            end

            dt = 1 / obj.fs;
            params = obj.cached_params;

            % Set Lyapunov time interval
            if isempty(obj.lya_T_interval)
                if obj.T_range(2) >= 15
                    obj.lya_T_interval = [obj.T_range(1) + 15, obj.T_range(2)]; % skip first 15 seconds
                else
                    obj.lya_T_interval = [obj.T_range(1), obj.T_range(2)]; % fallback for short simulations
                end
            end

            % Define RHS and Jacobian closures, dispatched through the subclass
            % numeric seam (eval_dynamics / eval_jacobian).
            params.u_interpolant = obj.u_interpolant;
            rhs = @(t, S) obj.eval_dynamics(t, S, params);
            jac = @(tt, S, p) obj.eval_jacobian(S, p);

            fprintf('Computing Lyapunov exponents using %s method\n', obj.lya_method);
            obj.lya_results = SRNNModelBase.compute_lyapunov_exponents_internal(obj.lya_method, obj.S_out, obj.t_out, dt, obj.fs, obj.lya_T_interval, params, obj.ode_opts, obj.ode_solver, rhs, obj.t_ex, obj.u_ex, jac);

            if isfield(obj.lya_results, 'LLE')
                fprintf('Largest Lyapunov Exponent: %.4f\n', obj.lya_results.LLE);
            end
        end

        function filter_lyapunov(obj)
            % FILTER_LYAPUNOV Apply lowpass filter to local Lyapunov exponent
            %
            % This filters the local_lya signal BEFORE decimation to avoid
            % edge effects that would occur if filtering after trimming.
            % Uses a Butterworth filter with parameters from obj properties.

            if isempty(obj.lya_results)
                return;
            end

            % Design filter (cutoff in Hz, normalized by Nyquist = lya_fs/2)
            Wn = obj.lya_filter_cutoff / (obj.lya_results.lya_fs / 2);
            [b, a] = butter(obj.lya_filter_order, Wn, 'low');

            % Filter local_lya for Benettin method
            if isfield(obj.lya_results, 'local_lya') && ~isempty(obj.lya_results.local_lya)
                obj.lya_results.local_lya = filtfilt(b, a, obj.lya_results.local_lya);
            end

            % Filter local_LE_spectrum_t for QR method (each column)
            if isfield(obj.lya_results, 'local_LE_spectrum_t') && ~isempty(obj.lya_results.local_LE_spectrum_t)
                for col = 1:size(obj.lya_results.local_LE_spectrum_t, 2)
                    obj.lya_results.local_LE_spectrum_t(:, col) = filtfilt(b, a, obj.lya_results.local_LE_spectrum_t(:, col));
                end
            end
        end

        function [fig_handle, ax_handles] = plot_eigenvalues(obj, J_times_sec)
            % PLOT_EIGENVALUES Plot Jacobian eigenvalues at specified times
            %
            % Usage:
            %   model.plot_eigenvalues([5, 10, 15])  % Times in seconds

            if isempty(obj.S_out)
                error('SRNNModel:NoStateData', 'State data required. Set store_full_state=true.');
            end

            params = obj.cached_params;

            % Convert times to indices
            J_times = round((J_times_sec - obj.t_out(1)) * obj.fs) + 1;
            J_times = unique(max(1, min(J_times, size(obj.S_out, 1))));

            fprintf('Computing Jacobian at %d time points\n', length(J_times));
            J_array = SRNNModelBase.compute_Jacobian_at_indices(obj.S_out, J_times, params, @(S, p) obj.eval_jacobian(S, p));

            % Compute eigenvalues
            n_plots = length(J_times);
            eigenvalues_all = cell(n_plots, 1);
            for i = 1:n_plots
                eigenvalues_all{i} = eig(J_array(:,:,i));
            end

            % Determine subplot layout
            if n_plots <= 4
                n_rows = 1;
                n_cols = n_plots;
            else
                n_cols = ceil(sqrt(n_plots));
                n_rows = ceil(n_plots / n_cols);
            end

            % Compute global axis limits
            all_real = [];
            all_imag = [];
            for i = 1:n_plots
                evals = eigenvalues_all{i};
                all_real = [all_real; real(evals)];
                all_imag = [all_imag; imag(evals)];
            end
            global_xlim = [min(all_real), max(all_real)];
            global_ylim = [min(all_imag), max(all_imag)];
            x_range = diff(global_xlim);
            y_range = diff(global_ylim);
            global_xlim = global_xlim + [-0.1, 0.1] * x_range;
            global_ylim = global_ylim + [-0.1, 0.1] * y_range;

            % Create figure
            fig_handle = figure('Position', [1312, 526, 600, 360]);
            ax_handles = zeros(n_plots, 1);

            for i = 1:n_plots
                ax = subplot(n_rows, n_cols, i);
                evals = eigenvalues_all{i};
                time_val = obj.t_out(J_times(i));
                ax_handles(i) = SRNNModelBase.plot_eigenvalues_helper(evals, ax, time_val, global_xlim, global_ylim, [], 1/obj.tau_d);
                set(ax_handles(i), 'Color', 'none');
            end

            linkaxes(ax_handles, 'xy');
        end

        function clear_results(obj)
            % CLEAR_RESULTS Free memory by clearing stored state data

            obj.t_out = [];
            obj.S_out = [];
            obj.plot_data = [];
            obj.lya_results = [];
            obj.has_run = false;
            fprintf('Results cleared.\n');
        end

        function reset(obj)
            % RESET Clear built state to allow rebuilding with new parameters
            %
            % Usage:
            %   model.reset();
            %   model.n = 200;  % Change parameters
            %   model.build();  % Rebuild with new settings

            obj.is_built = false;
            obj.W = [];
            obj.u_interpolant = [];
            obj.t_ex = [];
            obj.u_ex = [];
            obj.S0 = [];
            obj.cached_params = [];
            obj.clear_results();
            fprintf('Model reset. Modify parameters and call build() to reinitialize.\n');
        end

        function dS_dt = dynamics(obj, t, S)
            % DYNAMICS Compute the right-hand side of the SRNN ODE system
            %
            % This is a convenience method that wraps dynamics_fast.
            % For performance-critical code (e.g., ODE integration), use
            % dynamics_fast directly with a params struct.

            params = obj.cached_params;
            params.u_interpolant = obj.u_interpolant;
            dS_dt = obj.eval_dynamics(t, S, params);
        end
    end

    %% Protected Build Sub-Methods (overridable by subclasses)
    methods (Access = protected)
        function finalize_build(obj)
            % FINALIZE_BUILD Validate configuration and cache params
            %
            % Called after build_network() and build_stimulus(). Validates
            % the configuration and caches the params struct for fast access
            % during ODE integration. Subclasses typically do not override.

            % Validate configuration
            obj.validate();

            % Cache params struct for fast access in run/plot methods
            obj.cached_params = obj.get_params();

            obj.is_built = true;
            fprintf('Model built successfully. Ready to run.\n');
        end
    end

    %% Private Methods
    methods (Access = protected)
        function set_defaults(obj)
            % SET_DEFAULTS Initialize all properties to default values

            % Set default activation function (logisticSigmoid, centered at S_c).
            % Smooth sigmoid with unit slope at its center; S_c biases the resting
            % operating point onto the lower part of the curve (see logisticSigmoid).
            % S_a is retained for the piecewise static method but unused here.
            obj.activation_function = @(x) SRNNModelBase.logisticSigmoid(x, obj.S_c);
            obj.activation_function_derivative = @(x) SRNNModelBase.logisticSigmoidDerivative(x, obj.S_c);

            % Set default input configuration
            obj.input_config = struct();
            obj.input_config.n_steps = 3;
            obj.input_config.step_density = 0.2;
            obj.input_config.amp = 0.5;
            obj.input_config.no_stim_pattern = false(1, 3);
            obj.input_config.no_stim_pattern(1:2:end) = true;
            obj.input_config.intrinsic_drive = [];  % Will be set in build
            obj.input_config.positive_only = false;  % Default: allow positive and negative amplitudes

            % T_plot defaults to T_range (set in build if not specified)
            obj.T_plot = [];
        end

        function plot_spectrum_helper(~, ax, eigs, R, center, outlier_threshold)
            % PLOT_SPECTRUM_HELPER Helper function for plotting eigenvalue spectra
            %
            % Inputs:
            %   ax               - Axes handle to plot on
            %   eigs             - Vector of eigenvalues
            %   R                - Theoretical spectral radius
            %   center           - Center of the spectral disc (real part)
            %   outlier_threshold - Multiplier for R to classify far outliers

            % Compute distances from center for all eigenvalues
            distances = abs(eigs - center);

            % Plot interior eigenvalues (within R) as black circles
            mSize = 4;
            interior_mask = distances <= R;
            interior_eigs = eigs(interior_mask);
            plot(ax, real(interior_eigs), imag(interior_eigs), 'ko', 'MarkerSize', mSize, 'MarkerFaceColor', 'none', 'LineWidth', 0.5);
            hold(ax, 'on');

            % Plot theoretical radius circle (Eq 18)
            theta = linspace(0, 2*pi, 100);
            plot(ax, center + R*cos(theta), R*sin(theta), 'k-', 'LineWidth', 2);

            % Plot near outlier eigenvalues (between R and outlier_threshold*R) as black Xs
            near_outlier_mask = (distances > R) & (distances <= outlier_threshold * R);
            near_outlier_eigs = eigs(near_outlier_mask);
            if ~isempty(near_outlier_eigs)
                plot(ax, real(near_outlier_eigs), imag(near_outlier_eigs), 'kx', 'MarkerSize', mSize, 'LineWidth', 0.5);
            end

            % Plot far outlier eigenvalues (beyond outlier_threshold*R) as green filled circles
            far_outlier_mask = distances > outlier_threshold * R;
            far_outlier_eigs = eigs(far_outlier_mask);
            if ~isempty(far_outlier_eigs)
                plot(ax, real(far_outlier_eigs), imag(far_outlier_eigs), 'o', 'MarkerSize', mSize, 'MarkerFaceColor', [0 .7 0], 'MarkerEdgeColor', [0 .7 0]);
            end

            % Add axis lines through origin
            xl = xlim(ax);
            yl = ylim(ax);
            plot(ax, xl, [0 0], 'k-', 'LineWidth', 0.5);
            plot(ax, [0 0], yl, 'k-', 'LineWidth', 0.5);

            grid(ax, 'on');
            axis(ax, 'equal');
            hold(ax, 'off');
        end

        function [t_plot, S_plot, indices] = decimate_states(~, t_out, S_out, deci)
            % DECIMATE_STATES Decimates state trajectory for plotting
            %
            % Inputs:
            %   t_out - Time vector
            %   S_out - State matrix (nt x N)
            %   deci  - Decimation factor (integer)
            %
            % Outputs:
            %   t_plot  - Decimated time vector
            %   S_plot  - Decimated state matrix
            %   indices - Indices used for decimation

            indices = 1:deci:length(t_out);
            t_plot = t_out(indices);
            S_plot = S_out(indices, :);
        end

    end

    methods (Static, Access = protected)
        function s_out = trim_struct_data(s_in, dim, mask)
            % TRIM_STRUCT_DATA Helper to trim fields of a struct along a dimension
            s_out = s_in;
            fields = fieldnames(s_in);
            for i = 1:length(fields)
                val = s_in.(fields{i});
                if ~isempty(val)
                    if dim == 2
                        s_out.(fields{i}) = val(:, mask);
                    elseif dim == 3
                        s_out.(fields{i}) = val(:, :, mask);
                    end
                end
            end
        end

        function ax = plot_eigenvalues_helper(eigenvalues, ax, time_value, x_lim, y_lim, circle_params, scalebar_length)
            % PLOT_EIGENVALUES_HELPER Plot eigenvalue distribution on complex plane
            % Internalized from src/plotting/plot_eigenvalues.m (Option B: 3-tier outlier coloring)

            if nargin < 7, scalebar_length = 1; end
            if nargin < 6, circle_params = []; end
            if nargin < 5, y_lim = []; end
            if nargin < 4, x_lim = []; end

            axes(ax);
            mSize = 4;
            hold on;

            has_circle = ~isempty(circle_params) && isfield(circle_params, 'center') && isfield(circle_params, 'radius');

            if has_circle
                R = circle_params.radius;
                xc = real(circle_params.center);
                yc = imag(circle_params.center);

                if isfield(circle_params, 'outlier_threshold')
                    outlier_threshold = circle_params.outlier_threshold;
                else
                    outlier_threshold = 1.04;
                end

                distances = abs(eigenvalues - circle_params.center);

                % Interior eigenvalues (within R): black unfilled circles
                interior_mask = distances <= R;
                interior_eigs = eigenvalues(interior_mask);
                plot(real(interior_eigs), imag(interior_eigs), 'ko', 'MarkerSize', mSize, 'MarkerFaceColor', 'none', 'LineWidth', 0.5);

                % Near outlier eigenvalues (between R and outlier_threshold*R): black Xs
                near_outlier_mask = (distances > R) & (distances <= outlier_threshold * R);
                near_outlier_eigs = eigenvalues(near_outlier_mask);
                if ~isempty(near_outlier_eigs)
                    plot(real(near_outlier_eigs), imag(near_outlier_eigs), 'kx', 'MarkerSize', mSize, 'LineWidth', 0.5);
                end

                % Far outlier eigenvalues (beyond outlier_threshold*R): green filled circles
                far_outlier_mask = distances > outlier_threshold * R;
                far_outlier_eigs = eigenvalues(far_outlier_mask);
                if ~isempty(far_outlier_eigs)
                    plot(real(far_outlier_eigs), imag(far_outlier_eigs), 'o', 'MarkerSize', mSize, 'MarkerFaceColor', [0 .7 0], 'MarkerEdgeColor', [0 .7 0]);
                end

                % Draw theoretical radius as solid black circle
                theta = linspace(0, 2*pi, 100);
                plot(xc + R*cos(theta), yc + R*sin(theta), 'k-', 'LineWidth', 2);
            else
                % No circle params: plot all eigenvalues as black unfilled circles
                plot(real(eigenvalues), imag(eigenvalues), 'ko', 'MarkerSize', mSize, 'MarkerFaceColor', 'none', 'LineWidth', 0.5);
            end

            if isempty(x_lim), x_lim = xlim; end
            if x_lim(2) < 0, x_lim(2) = 0.05; end
            if isempty(y_lim), y_lim = ylim; end

            axis off;
            hold on;
            h_x = plot(x_lim, [0, 0], 'k', 'LineWidth', 1.25);
            h_y = plot([0, 0], y_lim, 'k', 'LineWidth', 1.25);
            uistack([h_x, h_y], 'bottom');

            text(1.02*x_lim(2), 0, ' Re($\lambda$)', 'Interpreter', 'latex', 'VerticalAlignment', 'middle');
            text(0, y_lim(2), 'Im($\lambda$)', 'Interpreter', 'latex', 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'center');

            % Scale bar in the lower left
            sb_x = x_lim(1) + 0.05 * diff(x_lim);
            sb_y = y_lim(1) + 0.05 * diff(y_lim);
            plot([sb_x, sb_x + scalebar_length], [sb_y, sb_y], 'k-', 'LineWidth', 2);
            text(sb_x + scalebar_length/2, sb_y, num2str(scalebar_length, '%g'), ...
                'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom');

            xlim(x_lim);
            ylim(y_lim);
            hold off;
            axis equal;
        end

        function lya_results = compute_lyapunov_exponents_internal(Lya_method, S_out, t_out, dt, fs, T_interval, params, opts, ode_solver, rhs_func, t_ex, u_ex, jac_func)
            % Compute Lyapunov exponents using Benettin or QR method.
            % Internalized from ConnectivityAdaptation/src/algorithms/Lyapunov/compute_lyapunov_exponents.m
            %
            % jac_func is the Jacobian seam handle @(tt, S, params) -> J supplied by
            % compute_lyapunov (dispatches to the subclass eval_jacobian); the QR
            % method uses it in place of a hardcoded static kernel.

            lya_results = struct();

            if strcmpi(Lya_method, 'none')
                return;
            end

            % Adjust lya_dt based on method
            if strcmpi(Lya_method, 'qr')
                lya_dt = 0.1;
            elseif strcmpi(Lya_method, 'benettin')
                lya_dt = 0.02;
            else
                lya_dt = 0.1;
            end

            lya_dt_vs_dt_factor = lya_dt / dt;

            if abs(round(lya_dt_vs_dt_factor) - lya_dt_vs_dt_factor) > 1e-11
                error(['lya_dt must be a multiple of dt. lya_dt_vs_dt_factor = ' num2str(lya_dt_vs_dt_factor)]);
            end

            if lya_dt_vs_dt_factor < 3
                error(['lya_dt must be 3*dt or more. lya_dt_vs_dt_factor = ' num2str(lya_dt_vs_dt_factor) ' Increase fs or increase lya_dt']);
            end

            lya_fs = 1 / lya_dt;

            switch lower(Lya_method)
                case 'benettin'
                    fprintf('Computing largest Lyapunov exponent using Benettin''s algorithm...\n');
                    d0 = 1e-3;
                    tic
                    [LLE, local_lya, finite_lya, t_lya] = SRNNModelBase.benettin_algorithm_internal(S_out, t_out, dt, fs, d0, T_interval, lya_dt, params, opts, rhs_func, t_ex, u_ex, ode_solver);
                    toc
                    lya_results.LLE = LLE;
                    lya_results.local_lya = local_lya;
                    lya_results.finite_lya = finite_lya;
                    lya_results.t_lya = t_lya;
                    lya_results.lya_dt = lya_dt;
                    lya_results.lya_fs = lya_fs;

                case 'qr'
                    fprintf('Computing full Lyapunov spectrum using QR decomposition method...\n');
                    tic
                    jacobian_wrapper = jac_func;
                    [LE_spectrum, local_LE_spectrum_t, finite_LE_spectrum_t, t_lya] = SRNNModelBase.lyapunov_spectrum_qr_internal(S_out, t_out, lya_dt, params, ode_solver, opts, jacobian_wrapper, T_interval, params.N_sys_eqs, fs);
                    toc
                    fprintf('Lyapunov Dimension: %.2f\n', SRNNModelBase.compute_kaplan_yorke_dimension_internal(LE_spectrum));
                    lya_results.LE_spectrum = LE_spectrum;
                    lya_results.local_LE_spectrum_t = local_LE_spectrum_t;
                    lya_results.finite_LE_spectrum_t = finite_LE_spectrum_t;
                    lya_results.t_lya = t_lya;
                    lya_results.params.N_sys_eqs = params.N_sys_eqs;

                    [sorted_LE, sort_idx] = sort(real(lya_results.LE_spectrum), 'descend');
                    lya_results.LE_spectrum = sorted_LE;
                    lya_results.local_LE_spectrum_t = lya_results.local_LE_spectrum_t(:, sort_idx);
                    lya_results.finite_LE_spectrum_t = lya_results.finite_LE_spectrum_t(:, sort_idx);
                    lya_results.sort_idx = sort_idx;
                    lya_results.lya_dt = lya_dt;
                    lya_results.lya_fs = lya_fs;
                    fprintf('Largest Lyapunov Exponent (sorted): %.4f\n', lya_results.LE_spectrum(1));

                otherwise
                    error('Unknown Lyapunov method: %s', Lya_method);
            end
        end

        function [LLE, local_lya, finite_lya, t_lya] = benettin_algorithm_internal(X, t, dt, fs, d0, T, lya_dt, params, ode_options, dynamics_func, t_ex, u_ex, ode_solver)
            % Benettin's algorithm to compute the largest Lyapunov exponent.
            % Internalized from ConnectivityAdaptation/src/algorithms/Lyapunov/benettin_algorithm.m

            if ~isscalar(lya_dt) || ~isnumeric(lya_dt) || lya_dt <= 0
                error('lya_dt must be a positive scalar.');
            end

            deci_lya = round(lya_dt * fs);
            if deci_lya < 1
                error('lya_dt * fs must result in at least 1 sample per Lyapunov interval.');
            end

            tau_lya = dt * deci_lya;
            t_lya = t(1:deci_lya:end);

            if t_lya(end) + tau_lya > T(2)
                t_lya(end) = [];
            end
            nt_lya = numel(t_lya);

            local_lya = zeros(nt_lya, 1);
            finite_lya = nan(nt_lya, 1);
            sum_log_stretching_factors = 0;

            n_state = size(X, 2);
            rnd_IC = randn(n_state, 1);
            pert = (rnd_IC ./ norm(rnd_IC)) .* d0;

            min_max_range = SRNNModelBase.get_minMaxRange_internal(params);
            min_bnds = min_max_range(:, 1);
            max_bnds = min_max_range(:, 2);

            for k = 1:nt_lya
                idx_start = (k - 1) * deci_lya + 1;
                idx_end = idx_start + deci_lya;

                X_start = X(idx_start, :).';
                X_k_pert = X_start + pert;

                idx_violates_min = ~isnan(min_bnds) & (X_k_pert < min_bnds);
                X_k_pert(idx_violates_min) = min_bnds(idx_violates_min);

                idx_violates_max = ~isnan(max_bnds) & (X_k_pert > max_bnds);
                X_k_pert(idx_violates_max) = max_bnds(idx_violates_max);

                t_seg_detailed = t_lya(k) + (0:dt:tau_lya);

                [~, X_pert_output_all_steps] = ode_solver(dynamics_func, t_seg_detailed, X_k_pert, ode_options);

                X_pert_end = X_pert_output_all_steps(end, :).';
                X_end = X(idx_end, :).';

                delta = X_pert_end - X_end;
                d_k = norm(delta);
                local_lya(k) = log(d_k / d0) / tau_lya;

                if ~isfinite(local_lya(k))
                    warning('System diverged at t=%f. Truncating results.', t_lya(k));
                    if k > 1
                        last_valid = finite_lya(1:k-1);
                        last_valid = last_valid(~isnan(last_valid));
                        if ~isempty(last_valid)
                            LLE = last_valid(end);
                        else
                            LLE = 0;
                        end
                    else
                        LLE = 0;
                    end
                    local_lya(k:end) = [];
                    finite_lya(k:end) = [];
                    t_lya(k:end) = [];
                    return;
                end

                pert = (delta ./ d_k) .* d0;

                if t_lya(k) >= 0
                    sum_log_stretching_factors = sum_log_stretching_factors + log(d_k / d0);
                    finite_lya(k, 1) = sum_log_stretching_factors / max(t_lya(k) + tau_lya, eps);
                end
            end

            last_valid = finite_lya(~isnan(finite_lya));
            if ~isempty(last_valid)
                LLE = last_valid(end);
            else
                LLE = 0;
            end
        end

        function [LE_spectrum, local_LE_spectrum_t, finite_LE_spectrum_t, t_lya_vec] = lyapunov_spectrum_qr_internal(X_fid_traj, t_fid_traj, lya_dt_interval, params, ode_solver, ode_options_main, jacobian_func_handle, T_full_interval, N_states_sys, fs_fid)
            % QR method for full Lyapunov spectrum.
            % Internalized from ConnectivityAdaptation/src/algorithms/Lyapunov/lyapunov_spectrum_qr.m

            fiducial_interpolants = cell(N_states_sys, 1);
            for i = 1:N_states_sys
                fiducial_interpolants{i} = griddedInterpolant(t_fid_traj, X_fid_traj(:, i), 'pchip');
            end

            dt_fid = 1 / fs_fid;

            fid_dt = diff(t_fid_traj);
            if ~isempty(fid_dt)
                nominal_dt = median(fid_dt);
                max_dt_dev = max(abs(fid_dt - nominal_dt));
                tol_dt_dev = max(1e-4 * max(nominal_dt, eps(nominal_dt)), eps(dt_fid));
                if max_dt_dev > tol_dt_dev
                    error('Fiducial trajectory timestamps are not uniformly spaced. Max deviation %.3g s exceeds tolerance %.3g s.', max_dt_dev, tol_dt_dev);
                end
            end

            deci_lya = round(lya_dt_interval / dt_fid);
            if deci_lya == 0
                error('lya_dt_interval is too small.');
            end
            tau_lya = dt_fid * deci_lya;

            t_lya_indices = 1:deci_lya:length(t_fid_traj);
            t_lya_vec = t_fid_traj(t_lya_indices);

            if ~isempty(t_lya_vec) && (t_lya_vec(end) + tau_lya > t_fid_traj(end) + eps(t_fid_traj(end)))
                t_lya_vec(end) = [];
                t_lya_indices(end) = [];
            end

            nt_lya = numel(t_lya_vec);
            if nt_lya == 0
                warning('No Lyapunov intervals could be formed.');
                LE_spectrum = nan(N_states_sys, 1);
                local_LE_spectrum_t = [];
                finite_LE_spectrum_t = [];
                return;
            end

            Q_current = eye(N_states_sys);
            sum_log_R_diag = zeros(N_states_sys, 1);

            local_LE_spectrum_t = zeros(nt_lya, N_states_sys);
            finite_LE_spectrum_t = nan(nt_lya, N_states_sys);

            total_positive_time_accumulated = 0;
            ode_options_var = ode_options_main;

            for k = 1:nt_lya
                t_start_segment = t_lya_vec(k);
                t_end_segment = t_start_segment + tau_lya;
                t_end_segment = min(t_end_segment, t_fid_traj(end));

                current_segment_duration = t_end_segment - t_start_segment;
                if current_segment_duration <= eps
                    if k > 1
                        local_LE_spectrum_t(k, :) = local_LE_spectrum_t(k-1, :);
                        finite_LE_spectrum_t(k, :) = finite_LE_spectrum_t(k-1, :);
                    else
                        local_LE_spectrum_t(k, :) = NaN;
                        finite_LE_spectrum_t(k, :) = NaN;
                    end
                    continue;
                end

                t_span_ode = [t_start_segment, t_end_segment];
                Psi0_vec = reshape(Q_current, [], 1);

                variational_eqs = @(tt, current_Psi_vec) SRNNModelBase.variational_eqs_ode_internal(tt, current_Psi_vec, fiducial_interpolants, N_states_sys, jacobian_func_handle, params);
                [~, Psi_solution_vec] = ode_solver(variational_eqs, t_span_ode, Psi0_vec, ode_options_var);

                Psi_evolved_matrix = reshape(Psi_solution_vec(end, :)', [N_states_sys, N_states_sys]);

                if any(~isfinite(Psi_evolved_matrix(:)))
                    warning('System diverged at t=%f. Truncating results.', t_start_segment);
                    if total_positive_time_accumulated > eps
                        LE_spectrum = sum_log_R_diag / total_positive_time_accumulated;
                    else
                        LE_spectrum = nan(N_states_sys, 1);
                    end
                    t_lya_vec(k:end) = [];
                    local_LE_spectrum_t(k:end, :) = [];
                    finite_LE_spectrum_t(k:end, :) = [];
                    return;
                end

                [Q_new, R_segment] = qr(Psi_evolved_matrix);
                diag_R = diag(R_segment);

                log_abs_diag_R = log(abs(diag_R));
                valid_diag_R = abs(diag_R) > eps;

                current_local_LEs = zeros(N_states_sys, 1);
                current_local_LEs(valid_diag_R) = log_abs_diag_R(valid_diag_R) / current_segment_duration;
                current_local_LEs(~valid_diag_R) = -Inf;
                local_LE_spectrum_t(k, :) = current_local_LEs';

                if t_start_segment >= -eps(0)
                    sum_log_R_diag(valid_diag_R) = sum_log_R_diag(valid_diag_R) + log_abs_diag_R(valid_diag_R);
                    total_positive_time_accumulated = total_positive_time_accumulated + current_segment_duration;
                end

                if total_positive_time_accumulated > eps
                    finite_LE_spectrum_t(k, :) = (sum_log_R_diag / total_positive_time_accumulated)';
                elseif k > 1 && t_start_segment >= -eps(0)
                    finite_LE_spectrum_t(k, :) = finite_LE_spectrum_t(k-1, :);
                else
                    finite_LE_spectrum_t(k, :) = NaN;
                end

                Q_current = Q_new;
            end

            if total_positive_time_accumulated > eps
                LE_spectrum = sum_log_R_diag / total_positive_time_accumulated;
            else
                warning('No accumulation over positive time for global LEs.');
                LE_spectrum = nan(N_states_sys, 1);
            end
        end

        function dPsi_vec_dt = variational_eqs_ode_internal(tt, current_Psi_vec, fiducial_interpolants, N_states_sys, jacobian_func_handle, params)
            % Variational ODE for QR method.
            X_fid_at_tt = zeros(N_states_sys, 1);
            for state_idx = 1:N_states_sys
                X_fid_at_tt(state_idx) = fiducial_interpolants{state_idx}(tt);
            end
            J_matrix = jacobian_func_handle(tt, X_fid_at_tt, params);
            Psi_matrix = reshape(current_Psi_vec, [N_states_sys, N_states_sys]);
            dPsi_matrix_dt = J_matrix * Psi_matrix;
            dPsi_vec_dt = reshape(dPsi_matrix_dt, [], 1);
        end

        function min_max_range = get_minMaxRange_internal(params)
            % Returns bounds per state variable for the state vector.
            % By default no hard bounds (NaN); length matches the state dimension.
            % Uses params.N_sys_eqs (populated by each subclass's get_params) so this
            % stays type-agnostic (no E/I state-layout assumptions). Value-identical
            % to the former n_E/n_I/n_a/n_b reconstruction.
            min_max_range = nan(params.N_sys_eqs, 2);
        end

        function D_KY = compute_kaplan_yorke_dimension_internal(lambda)
            % Compute Kaplan-Yorke (Lyapunov) dimension from spectrum.
            lambda = sort(lambda, 'descend');
            cumsum_lambda = cumsum(lambda);
            j = find(cumsum_lambda >= 0, 1, 'last');

            if isempty(j)
                D_KY = 0;
            elseif j == length(lambda)
                D_KY = length(lambda);
            else
                D_KY = j + cumsum_lambda(j) / abs(lambda(j + 1));
            end
        end
    end

    %% ====================================================================
    %              INTERNALIZED ACTIVATION FUNCTIONS
    % =====================================================================
    % Internalized from src/nonlinearities/ to make SRNNModel2 standalone.

    methods (Static)
        function y = piecewiseSigmoid(x, a, c, r_max)
            % PIECEWISESIGMOID A piecewise linear/quadratic sigmoid activation function.
            % Internalized from src/nonlinearities/piecewiseSigmoid.m
            %
            % Optional scalar r_max (default 1) raises the saturation ceiling from 1
            % to r_max by lengthening the unit-slope linear band; the threshold and
            % bottom soft shoulder are unchanged, so the low output region is
            % identical to the r_max=1 form. See also piecewiseSigmoidDerivative.

            if nargin < 4 || isempty(r_max), r_max = 1; end
            if a < 0 || a > 1
                error('Parameter "a" must be between 0 and 1.');
            end
            a = a / 2;

            if a == 0.5
                y_linear = (x - c) + 0.5;
                y = min(max(y_linear, 0), r_max);
            else
                y = zeros(size(x));
                k = 0.5 / (1 - 2*a);
                x1 = c + a - 1;
                x2 = c - a;
                x3 = c + r_max - 1 + a;
                x4 = c + r_max - a;

                mask_left_quad = (x >= x1) & (x < x2);
                mask_linear = (x >= x2) & (x <= x3);
                mask_right_quad = (x > x3) & (x <= x4);
                mask_right_sat = (x > x4);

                if any(mask_left_quad, 'all')
                    y(mask_left_quad) = k * (x(mask_left_quad) - x1).^2;
                end
                if any(mask_linear, 'all')
                    y(mask_linear) = (x(mask_linear) - c) + 0.5;
                end
                if any(mask_right_quad, 'all')
                    y(mask_right_quad) = r_max - k * (x(mask_right_quad) - x4).^2;
                end
                if any(mask_right_sat, 'all')
                    y(mask_right_sat) = r_max;
                end
            end
        end

        function dy = piecewiseSigmoidDerivative(x, a, c, r_max)
            % PIECEWISESIGMOIDDERIVATIVE First derivative of the piecewise sigmoid.
            % Internalized from src/nonlinearities/piecewiseSigmoidDerivative.m
            % Optional scalar r_max (default 1) matches piecewiseSigmoid's ceiling.

            if nargin < 4 || isempty(r_max), r_max = 1; end
            if a < 0 || a > 1
                error('Parameter "a" must be between 0 and 1.');
            end
            a = a / 2;
            dy = zeros(size(x), 'like', x);

            if a == 0.5
                breakpoint1 = c - 0.5;
                breakpoint2 = c + r_max - 0.5;
                mask_linear = (x >= breakpoint1) & (x <= breakpoint2);
                dy(mask_linear) = 1;
            else
                k = 0.5 / (1 - 2*a);
                x1 = c + a - 1;
                x2 = c - a;
                x3 = c + r_max - 1 + a;
                x4 = c + r_max - a;

                mask_left_quad = (x >= x1) & (x < x2);
                mask_linear = (x >= x2) & (x <= x3);
                mask_right_quad = (x > x3) & (x <= x4);

                if any(mask_left_quad)
                    dy(mask_left_quad) = 2 * k * (x(mask_left_quad) - x1);
                end
                if any(mask_linear)
                    dy(mask_linear) = 1;
                end
                if any(mask_right_quad)
                    dy(mask_right_quad) = -2 * k * (x(mask_right_quad) - x4);
                end
            end
        end

        function y = logisticSigmoid(x, c)
            % LOGISTICSIGMOID Logistic sigmoid activation with unit slope at its center.
            %   y = logisticSigmoid(x, c) = 1/(1+exp(-4*(x-c)))
            %   Range (0,1); y(c)=0.5; slope 1 at x=c (the factor 4 sets that).
            %   c is an optional center/bias (default 0): c>0 shifts the
            %   inflection to positive x, so at the resting point (x~0) the
            %   network sits on the LOWER part of the curve.
            if nargin < 2, c = 0; end
            y = 1 ./ (1 + exp(-4 * (x - c)));
        end

        function dy = logisticSigmoidDerivative(x, c)
            % LOGISTICSIGMOIDDERIVATIVE First derivative of logisticSigmoid.
            %   dy = 4*sigma*(1-sigma) with sigma = 1/(1+exp(-4*(x-c))).
            %   c is an optional center/bias (default 0); dy(c)=1.
            if nargin < 2, c = 0; end
            sigmoid_val = 1 ./ (1 + exp(-4 * (x - c)));
            dy = 4 * sigmoid_val .* (1 - sigmoid_val);
        end

        function y = tanhActivation(x)
            % TANHACTIVATION Hyperbolic tangent activation function.
            % Internalized from src/nonlinearities/tanhActivation.m
            y = tanh(x);
        end

        function dy = tanhActivationDerivative(x)
            % TANHACTIVATIONDERIVATIVE First derivative of the hyperbolic tangent.
            % Internalized from src/nonlinearities/tanhActivationDerivative.m
            dy = 1 - tanh(x).^2;
        end
    end

    %% ====================================================================
    %              INTERNALIZED STIMULUS GENERATION
    % =====================================================================
    % Internalized from src/generate_stimulus/ to make SRNNModel2 standalone.


    %% ====================================================================
    %              INTERNALIZED JACOBIAN COMPUTATION
    % =====================================================================
    % Internalized from src/algorithms/Jacobian/ to make SRNNModel2 standalone.

    methods (Static)
        function J_array = compute_Jacobian_at_indices(S_out, J_times, params, jac_fn)
            % COMPUTE_JACOBIAN_AT_INDICES Computes Jacobian matrices at multiple time indices.
            % Internalized from src/algorithms/Jacobian/compute_Jacobian_at_indices.m
            %
            % jac_fn is the Jacobian seam handle @(S, params) -> J (dispatches to the
            % caller's eval_jacobian); replaces the former hardcoded static kernel.

            N_sys_eqs = size(S_out, 2);
            n_times = length(J_times);

            nt = size(S_out, 1);
            if any(J_times < 1) || any(J_times > nt)
                error('J_times contains invalid indices. Must be between 1 and %d', nt);
            end

            J_array = zeros(N_sys_eqs, N_sys_eqs, n_times);

            for i = 1:n_times
                S = S_out(J_times(i), :)';
                J_array(:,:,i) = full(jac_fn(S, params));
            end
        end
    end


    %% ====================================================================
    %              INTERNALIZED PLOTTING FUNCTIONS
    % =====================================================================
    % Internalized from src/plotting/ to make SRNNModel2 standalone.

    methods (Static, Access = protected)
        function plot_lyapunov(lya_results, Lya_method, plot_options)
            % PLOT_LYAPUNOV Plot Lyapunov exponent(s) on current axes.
            % Internalized from src/plotting/plot_lyapunov.m

            if nargin < 3
                plot_options = {'local', 'asym', 'EOC', 'value'};
            end

            if strcmpi(Lya_method, 'benettin')
                valid_options = {'local', 'asym', 'EOC', 'value'};
                if ~iscell(plot_options)
                    error('plot_options must be a cell array of strings');
                end
                for i = 1:length(plot_options)
                    if strcmpi(plot_options{i}, 'filtered')
                        error(['The ''filtered'' option has been removed. ', ...
                            'Filtering now occurs in SRNNModel before decimation. ', ...
                            'Set model.filter_local_lya = true and use ''local'' instead.']);
                    end
                    if ~any(strcmpi(plot_options{i}, valid_options))
                        error('Invalid plot_option: %s. Valid options are: %s', ...
                            plot_options{i}, strjoin(valid_options, ', '));
                    end
                end
            end

            if strcmpi(Lya_method, 'benettin')
                plot_local = any(strcmpi('local', plot_options));
                plot_asym = any(strcmpi('asym', plot_options));
                plot_EOC = any(strcmpi('EOC', plot_options));
                plot_value = any(strcmpi('value', plot_options));

                legend_entries = {};
                plot_started = false;

                if plot_local
                    colors = lines(1);
                    plot(lya_results.t_lya, lya_results.local_lya, 'Color', colors(1,:))
                    hold on
                    plot_started = true;
                    legend_entries{end+1} = 'Local LLE';
                end

                if plot_asym
                    if ~plot_started, hold on; plot_started = true; end
                    plot([lya_results.t_lya(1), lya_results.t_lya(end)], ...
                        [lya_results.LLE, lya_results.LLE], '--r', 'LineWidth', 1.5);
                end

                if plot_EOC
                    if ~plot_started, hold on; plot_started = true; end
                    plot([lya_results.t_lya(1), lya_results.t_lya(end)], [0, 0], '--k');
                end

                ylabel('\lambda_1')

                if plot_value
                    ylims = ylim;
                    xlims = xlim;
                    text_y = 0.05 * (ylims(2) - ylims(1));
                    text_x = xlims(2);
                    text(text_x, text_y, ['$\lambda_1 = ' sprintf('%.2f', lya_results.LLE) '$'], ...
                        'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom', ...
                        'Interpreter', 'latex');
                end

                hold off
                box off

            elseif strcmpi(Lya_method, 'qr')
                plot_data = lya_results.local_LE_spectrum_t(:, end:-1:1);
                line_handles = plot(lya_results.t_lya, plot_data);
                line_handles = line_handles(end:-1:1);

                hold on
                yline(0, '--k')
                ylabel('\lambda_1')

                legend_count = min(5, lya_results.params.N_sys_eqs);
                legend_entries = cell(1, legend_count);
                for i = 1:legend_count
                    legend_entries{i} = sprintf('\\lambda_{%d} = %.3f', i, lya_results.LE_spectrum(i));
                end
                legend(line_handles(1:legend_count), legend_entries, 'Location', 'best')
                hold off
                box off
            end
        end

        function plot_lines_with_colormap(t, data, cmap, varargin)
            % PLOT_LINES_WITH_COLORMAP Plot multiple lines with explicit colormap assignment.
            % Internalized from src/plotting/plot_lines_with_colormap.m
            if isempty(data), return; end
            n_lines = size(data, 1);
            n_colors = size(cmap, 1);
            hold on;
            for i = 1:n_lines
                color_idx = mod(i - 1, n_colors) + 1;
                plot(t, data(i, :), 'Color', cmap(color_idx, :), varargin{:});
            end
        end

    end
end

