function cfg = ied_base_config()
% IED_BASE_CONFIG Frozen working base selected October 1: exploratory run13.
% Explicit values keep this independent of later changes to the trial catalog.
cfg=struct('id',13,'n',350,'f',[.7 .3],'indegree',30, ...
    'mu',[7 -7;7 -7],'sigma',1.5*ones(2),'gain',1, ...
    'Sc',[.45 .45],'Sc_sd',[.15 .15],'tau_a',[.40 .75], ...
    'tau_spread',[.70 .50],'c',[.5 .5], ...
    'std_rec',2,'std_rel',.25,'std_on_I',false, ...
    'noise',.025,'fs',400,'duration',50,'warmup',10,'K',25, ...
    'seed',42,'noise_seed',224779,'topology','modular','groups',5, ...
    'p_within',.30,'p_between',.003,'wE',.60,'wI',-.40, ...
    'w_sd',.08,'between_scale',.5, ...
    'rationale','Frozen run13 working base selected October1,2026. Localized modest excursions; not a completed sparse IED model.', ...
    'interpretation','Selected working base; further validation pending.');
end
